export enum OrganizationType {
    DAVINCI = 'DAVINCI',
    FIR_OWNER = 'FIR_OWNER',
    OPERATOR = 'OPERATOR',
}

export enum Role {
    DAVINCI_ADMIN = 'DAVINCI_ADMIN',
    DAVINCI_MANAGER = 'DAVINCI_MANAGER',
    DAVINCI_OPERATIONS = 'DAVINCI_OPERATIONS',
    DAVINCI_FINANCE = 'DAVINCI_FINANCE',
    FIR_ADMIN = 'FIR_ADMIN',
    FIR_MANAGER = 'FIR_MANAGER',
    FIR_FINANCE = 'FIR_FINANCE',
    OPERATOR_ADMIN = 'OPERATOR_ADMIN',
    OPERATOR_MANAGER = 'OPERATOR_MANAGER',
    OPERATOR_FINANCE = 'OPERATOR_FINANCE',
    SUPER_ADMIN = 'SUPER_ADMIN',
}

export enum Permission {
    INVOICE_VIEW = 'INVOICE_VIEW',
    INVOICE_VIEW_OVERDUE_ONLY = 'INVOICE_VIEW_OVERDUE_ONLY',
    INVOICE_EDIT = 'INVOICE_EDIT',
    INVOICE_EXPORT = 'INVOICE_EXPORT',
    FLIGHT_TRACKER_VIEW = 'FLIGHT_TRACKER_VIEW',
    FLIGHT_TRACKER_VIEW_FIR_DATA = 'FLIGHT_TRACKER_VIEW_FIR_DATA',
    FLIGHT_TRACKER_VIEW_GLOBAL = 'FLIGHT_TRACKER_VIEW_GLOBAL',
    MANUAL_REVIEW_VIEW = 'MANUAL_REVIEW_VIEW',
    MANUAL_REVIEW_EDIT = 'MANUAL_REVIEW_EDIT',
    KYC_VIEW = 'KYC_VIEW',
    KYC_EDIT = 'KYC_EDIT',
    USER_VIEW = 'USER_VIEW',
    USER_CREATE = 'USER_CREATE',
    USER_UPDATE = 'USER_UPDATE',
    USER_DELETE = 'USER_DELETE',
    USER_MANAGE_PERMISSIONS = 'USER_MANAGE_PERMISSIONS',
    SYSTEM_ADMIN = 'SYSTEM_ADMIN',
    AUDIT_VIEW = 'AUDIT_VIEW',
    ROLE_MANAGE = 'ROLE_MANAGE',
}
